coverage:
  precision: 2
  round: down
  threshold: 80

ignore:
  - cmd/myapp/main.go
  - domain/*
  - infraestructure/database/*
  - infraestructure/persistence/pedido_repository.go
  - infraestructure/persistence/produto_repository.go
  - usecase/pedido/usecase.go
