version: "3.9"
services:
  pedido-app:
    image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido-app
    ports: 
      - 3333:3333
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - pedido-db
      - pedido-redis
  pedido-db:
    image: postgres:alpine3.19
    container_name: pedido-db
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
networks:
  default:
    driver: bridge
