version: "3.9"
services:
  pedido-app:
    image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido-app
    ports: 
      - 3333:3333
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - pedido-db
      - pedido-redis
    networks:
      - pedido-bridge
  pedido-db:
    image: postgres:alpine3.19
    container_name: pedido-db
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    networks:
      - pedido-bridge
  pedido-redis:
    image: redis:latest
    container_name: pedido-redis
    ports:
      - "6379:6379"
    networks:
      - pedido-bridge
    restart: always
networks:
  pedido-bridge:
    driver: bridge
