apiVersion: v1
kind: Service
metadata:
  name: svc-pedido-app
spec:
  type: LoadBalancer
  selector:
    app: pedido-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30003  # Port on each node
    targetPort: 3333